version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: perfex-api
    environment:
      POSTGRES_DB: perfex-api
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
